### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by MAGPIESHADOW** [ShadowArc147/helpercode#1]
**Attempted to add following lines:** 

# Separate locations based on direction and calculate the probability for each
left_locations = {location: data["frequency"] for location, data in locations.items() if data["direction"] == "left"}
right_locations = {location: data["frequency"] for location, data in locations.items() if data["direction"] == "right"}

**I was aiming to have the list of locations with a corresponding direction of "left" or "right" to indicate that the location is in the direction of left or right so when you  - Choose a direction (Right): right - the only output from left / right are the locations that are in the direction of left / right.** 

**If that doesn't make sense I'll pop through!** 

**I thought this may work...**

# Print the ordered list of locations with the direction
print("\nOrdered list of locations based on your decision:")
for i, loc in enumerate(ordered_locations):
    direction = "Left" if decision == "left" else "Right"
    print(f"{loc['name']} - Probability: {loc['probability']:.1f} - Direction: {direction}")

**It didn't.** 

**This is the whole script:** 

def get_user_decision():
    while True:
        decision = input("Choose a direction (Right): ").strip().lower()
        if decision in ["left", "right"]:
            return decision
        else:
            print("Invalid input. Please enter 'Left' or 'Right'.")

# Initial locations and their probabilities
locations = [
    {"name": "Worcester Walk Memorial Playground", "probability" : 0.4, "direction" : "right"},
    {"name": "Gamekeepers Inn", "probability": 0.3, "direction" : "left"},
    {"name": "Premier", "probability": 0.2, "direction" : "right"},
    {"name": "Cancer Research UK", "probability": 0.1, "direction" : "left"}
]

# Sort locations by probability in descending order
sorted_locations = sorted(locations, key=lambda x: x["probability"], reverse=True)

decision = get_user_decision()

# Order locations based on user's decision
if decision == "left":
    ordered_locations = sorted_locations
else:  # decision == "right"
    ordered_locations = list(reversed(sorted_locations))

# Print the ordered list of locations with the direction
print("\nOrdered list of locations based on your decision:")
for i, loc in enumerate(ordered_locations):
    direction = "Left" if decision == "left" else "Right"
    print(f"{loc['name']} - Probability: {loc['probability']:.1f} - Direction: {direction}")

# Print the ordered list of locations
print("\nOrdered list of locations based on your decision:")
for loc in ordered_locations:
    print(f"{loc['name']} - Probability: {loc['probability']}")

**Comment by ShadowArc147** [comment]
Cool, whats the error message you're getting?

**Comment by MAGPIESHADOW** [comment]
No longer getting an error message with that new string of print("\nOrdered list locations based on your decision:")
but it doesn't separate them into left / right it just labels them all as right or right depending on what you type in:

Choose a direction (Right): left

Ordered list of locations based on your decision:
Worcester Walk Memorial Playground - Probability: 0.4 - Direction: Left
Gamekeepers Inn - Probability: 0.3 - Direction: Left
Premier - Probability: 0.2 - Direction: Left
Cancer Research UK - Probability: 0.1 - Direction: Left

Ordered list of locations based on your decision:
Worcester Walk Memorial Playground - Probability: 0.4
Gamekeepers Inn - Probability: 0.3
Premier - Probability: 0.2
Cancer Research UK - Probability: 0.1
PS C:\Users\LucyC\Desktop\Project MAGPIE>

**Comment by ShadowArc147** [comment]
def get_user_decision():
    while True:
        decision = input("Choose a direction (left or right): ").strip().lower()
        if decision in ["left", "right"]:
            return decision
        else:
            print("Invalid input. Please enter 'left' or 'right'.")

# Initial locations and their probabilities
locations = [
    {"name": "Worcester Walk Memorial Playground", "probability": 0.4, "direction": "right"},
    {"name": "Gamekeepers Inn", "probability": 0.3, "direction": "left"},
    {"name": "Premier", "probability": 0.2, "direction": "right"},
    {"name": "Cancer Research UK", "probability": 0.1, "direction": "left"}
]

# Sort locations by probability in descending order
sorted_locations = sorted(locations, key=lambda x: x["probability"], reverse=True)

# Get user decision
decision = get_user_decision()

# Filter locations based on user's decision
filtered_locations = [loc for loc in sorted_locations if loc["direction"] == decision]

# Print the ordered list of locations based on the user's decision
print("\nOrdered list of locations based on your decision:")
for loc in filtered_locations:
    print(f"{loc['name']} - Probability: {loc['probability']:.1f} - Direction: {loc['direction'].capitalize()}")
    
    
    
    Try this :)

**Comment by ShadowArc147** [comment]
```
try this code :)

def get_user_decision():
    while True:
        decision = input("Choose a direction (left or right): ").strip().lower()
        if decision in ["left", "right"]:
            return decision
        else:
            print("Invalid input. Please enter 'left' or 'right'.")
``
# Initial locations and their probabilities
locations = [
    {"name": "Worcester Walk Memorial Playground", "probability": 0.4, "direction": "right"},
    {"name": "Gamekeepers Inn", "probability": 0.3, "direction": "left"},
    {"name": "Premier", "probability": 0.2, "direction": "right"},
    {"name": "Cancer Research UK", "probability": 0.1, "direction": "left"}
]

# Sort locations by probability in descending order
sorted_locations = sorted(locations, key=lambda x: x["probability"], reverse=True)

# Get user decision
decision = get_user_decision()

# Filter locations based on user's decision
filtered_locations = [loc for loc in sorted_locations if loc["direction"] == decision]

# Print the ordered list of locations based on the user's decision
print("\nOrdered list of locations based on your decision:")
for loc in filtered_locations:
    print(f"{loc['name']} - Probability: {loc['probability']:.1f} - Direction: {loc['direction'].capitalize()}")
```

**Comment by MAGPIESHADOW** [comment]
You genius!

**Comment by ShadowArc147** [comment]
```

import random

def get_user_decision():
    while True:
        decision = input("Choose a direction (left or right): ").strip().lower()
        if decision in ["left", "right"]:
            return decision
        else:
            print("Invalid input. Please enter 'left' or 'right'.")

# Initial locations and their probabilities

probability = random.randrange(0.01, 0.9)
locations = [
    {"name": "Worcester Walk Memorial Playground", "probability": probability, "direction": "right"},
    {"name": "Gamekeepers Inn", "probability": probability, "direction": "left"},
    {"name": "Premier", "probability": probability, "direction": "right"},
    {"name": "Cancer Research UK", "probability": probability, "direction": "left"}
]

# Sort locations by probability in descending order
sorted_locations = sorted(locations, key=lambda x: x["probability"], reverse=True)

# Get user decision
decision = get_user_decision()

# Filter locations based on user's decision
filtered_locations = [loc for loc in sorted_locations if loc["direction"] == decision]

# Print the ordered list of locations based on the user's decision
print("\nOrdered list of locations based on your decision:")
for loc in filtered_locations:
    print(f"{loc['name']} - Probability: {loc['probability']:.1f} - Direction: {loc['direction'].capitalize()}")
```

**Comment by MAGPIESHADOW** [comment]
PS C:\Users\LucyC\Desktop\Project MAGPIE> & C:/Python312/python.exe c:/Users/LucyC/Downloads/formatted_locations.py
Traceback (most recent call last):
  File "c:\Users\LucyC\Downloads\formatted_locations.py", line 13, in <module>
    probability=random.randrange(0.01-0.9)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\random.py", line 301, in randrange
    istart = _index(start)
             ^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer

**Comment by MAGPIESHADOW** [comment]
Start of code example:

import random

def get_user_decision():
    while True:
        decision = input("Choose a direction (left or right): ").strip().lower()
        if decision in ["left", "right"]:
            return decision
        else:
            print("Invalid input. Please enter 'left' or 'right'.")


# Initial locations and their probabilities
probability=random.randrange(0.01-0.9)
locations = [

{
        "name": "The New Inn",
        "probability": probability,
        "direction": "right"
    },
    {
        "name": "Wye Dean Cottage",
        "probability": probability,
        "direction": "right"

**Comment by MAGPIESHADOW** [comment]
I've been dumb, one mo let me try something

**Comment by MAGPIESHADOW** [comment]
Changed the range to (0.01, 0.9) 

but still same error
